# Generated by Django 6.0.8 on 2026-09-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_alt_text_ru_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
    ]
