# Generated by Django 6.0.8 on 2026-09-17 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(default='Toshkent', editable=False, max_length=50)),
                ('district', models.CharField(choices=[('BEKTEMIR', 'Bektemir'), ('CHILONZOR', 'Chilonzor'), ('MIROBOD', 'Mirobod'), ('MIRZO_ULUGBEK', "Mirzo Ulug'bek"), ('OLMAZOR', 'Olmazor'), ('SERGELI', 'Sergeli'), ('SHAYXONTOHUR', 'Shayxontohur'), ('UCHTEPA', 'Uchtepa'), ('YAKKASAROY', 'Yakkasaroy'), ('YASHNOBOD', 'Yashnobod'), ('YUNUSOBOD', 'Yunusobod'), ('YANGIHAYOT', 'Yangihayot')], max_length=30)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=50)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('SHIPPING', 'Yetkazilmoqda'), ('DELIVERED', 'Yetkazilgan'), ('CANCELLED', 'Bekor qilingan')], default='NEW', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', "To'lanmagan"), ('PAID', "To'langan")], default='UNPAID', max_length=20)),
                ('payment_method', models.CharField(default='CASH_ON_DELIVERY', editable=False, max_length=30)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('stock_restored', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_marked_paid', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('SHIPPING', 'Yetkazilmoqda'), ('DELIVERED', 'Yetkazilgan'), ('CANCELLED', 'Bekor qilingan')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
