# Generated by Django 6.1.1 on 2026-09-21 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('items_data', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('step', models.CharField(default='WAITING_PHONE', max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('BEKTEMIR', 'Bektemir'), ('CHILONZOR', 'Chilonzor'), ('MIROBOD', 'Mirobod'), ('MIRZO_ULUGBEK', "Mirzo Ulug'bek"), ('OLMAZOR', 'Olmazor'), ('SERGELI', 'Sergeli'), ('SHAYXONTOHUR', 'Shayxontohur'), ('UCHTEPA', 'Uchtepa'), ('YAKKASAROY', 'Yakkasaroy'), ('YASHNOBOD', 'Yashnobod'), ('YUNUSOBOD', 'Yunusobod'), ('YANGIHAYOT', 'Yangihayot')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
